In [1]:
import pandas as pd
import numpy as np
#import matplotlib as plt
from sklearn.model_selection import KFold
from sklearn import metrics
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


In [2]:
df = pd.read_excel("dataset.xlsx")
df.head()
X = df['Statement']
Y = df['Label']

In [3]:
df = pd.read_excel("dataset.xlsx")
df.head()

Label                                       Statement
0      1  ৮ বছর আগে আমি মারা যেতাম যদি আমার মা না থাকতো 
1      1   যদি মরে যেতে পারতাম বা অদৃশ্য হয়ে যেতে পারতাম
2      1                         যদি কখনো জন্মই না নিতাম
3      1            আমি আনুষ্ঠানিকভাবে নিজেকে হত্যা করবো
4      1                               এটা আমার সময়সীমা

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
vect.fit(X)
X = vect.transform(X)
#X = vect.fit_transform(df['Statement'])

In [5]:
from scipy.sparse import coo_matrix
X_sparse = coo_matrix(X)
from sklearn.utils import shuffle
X, X_sparse, Y = shuffle(X, X_sparse, Y, random_state=0)
print(X)

  (0, 26)	0.4293725821096384
  (0, 32)	0.20166636026752988
  (0, 37)	0.4622785216961883
  (0, 61)	0.5951960901586362
  (0, 205)	0.4549835683925388
  (1, 8)	0.3232749600516551
  (1, 96)	0.5125349758327831
  (1, 114)	0.5826198640492137
  (1, 239)	0.5416228325753678
  (2, 5)	0.34986246325622405
  (2, 29)	0.24925145116399727
  (2, 58)	0.3045909751399517
  (2, 73)	0.26500245686016394
  (2, 84)	0.16354868531500774
  (2, 116)	0.22276932826413448
  (2, 144)	0.3310730980398145
  (2, 198)	0.4280959978148139
  (2, 249)	0.37634458615608685
  (2, 267)	0.24474532310169186
  (2, 270)	0.2858016099235421
  (3, 32)	0.3336911269783553
  (3, 37)	0.3824590295526996
  (3, 81)	0.49242633683344245
  (3, 116)	0.3601468632665536
  (3, 227)	0.6084290116041327
  :	:
  (227, 59)	0.5437065589632045
  (227, 65)	0.6776628588343349
  (228, 32)	0.18175598601469195
  (228, 80)	0.5364328095938291
  (228, 202)	0.4897936089915944
  (228, 229)	0.6628022502451896
  (229, 164)	0.5979755639304695
  (229, 182)	0.801514332337255

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=10)
kf.get_n_splits(X)
print(kf)

KFold(n_splits=10, random_state=None, shuffle=False)


In [7]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

TRAIN: [ 24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41
  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59
  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113
 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131
 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149
 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167
 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185
 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203
 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221
 222 223 224 225 226 227 228 229 230 231 232] TEST: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
TRAIN: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13 

In [8]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
%time logreg.fit(X_train, y_train)
y_pred_class = logreg.predict(X_test)
#y_pred_prob = logreg.predict_proba(X_test)[:, 1]
y_pred_prob

Wall time: 739 ms


array([0.58617306, 0.62735599, 0.72767471, 0.51859577, 0.62570807,
       0.7289975 , 0.55465739, 0.4479742 , 0.60627219, 0.64744012,
       0.5429601 , 0.66943184, 0.63032035, 0.68673142, 0.53491826,
       0.58698677, 0.62629989, 0.65779311, 0.70465561, 0.48602594,
       0.58696142, 0.45953252, 0.53444453])

In [10]:
print('\nIn Logistic Regression is:',round(accuracy_score(y_test,y_pred_class)*100,3),'%','\n-------------------------------')
print('Confusion matrix:\n',confusion_matrix(y_test,y_pred_class),'\n')
print('Classification report:\n',classification_report(y_test,y_pred_class))




In Logistic Regression is: 47.826 % 
-------------------------------
Confusion matrix:
 [[ 2 11]
 [ 1  9]] 

Classification report:
              precision    recall  f1-score   support

          0       0.67      0.15      0.25        13
          1       0.45      0.90      0.60        10

avg / total       0.57      0.48      0.40        23



In [11]:
from sklearn import tree
dt=tree.DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_pred =dt.predict(X_test)
print(y_pred)

[1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1]


In [12]:
print('\nIn Decision tree accuacy is:',round(accuracy_score(y_test,y_pred)*100,3),'%','\n-------------------------------')
print('Confusion matrix:\n',confusion_matrix(y_test,y_pred),'\n')
print('Classification report:\n',classification_report(y_test,y_pred))


In Decision tree accuacy is: 30.435 % 
-------------------------------
Confusion matrix:
 [[ 1 12]
 [ 4  6]] 

Classification report:
              precision    recall  f1-score   support

          0       0.20      0.08      0.11        13
          1       0.33      0.60      0.43        10

avg / total       0.26      0.30      0.25        23



In [14]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
%time nb.fit(X_train, y_train)
y_pred_class = nb.predict(X_test)
#print(metrics.accuracy_score(y_test, y_pred_class))



Wall time: 0 ns


In [15]:
print('\nIn naive bayes accuacy is:',round(accuracy_score(y_test,y_pred_class)*100,3),'%','\n-------------------------------')
print('Confusion matrix:\n',confusion_matrix(y_test,y_pred_class),'\n')
print('Classification report:\n',classification_report(y_test,y_pred_class))


In naive bayes accuacy is: 52.174 % 
-------------------------------
Confusion matrix:
 [[ 3 10]
 [ 1  9]] 

Classification report:
              precision    recall  f1-score   support

          0       0.75      0.23      0.35        13
          1       0.47      0.90      0.62        10

avg / total       0.63      0.52      0.47        23



In [17]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
#print("Precision:",metrics.precision_score(y_test, y_pred))
#print("Recall:",metrics.recall_score(y_test, y_pred))
#print("Confusion:",metrics.confusion_matrix(y_test, y_pred))
print('Classification report:\n',classification_report(y_test,y_pred_class))


Accuracy: 0.5217391304347826
Classification report:
              precision    recall  f1-score   support

          0       0.75      0.23      0.35        13
          1       0.47      0.90      0.62        10

avg / total       0.63      0.52      0.47        23

